### ISSUE TITLE
Request for code

### ISSUE THREAD

**Issue by dominCodebug** [monajati/BERTHop#2]
Dear author, after reading your paper《BERTHop: An Effective Vision-and-Language Model for Chest X-ray Disease Diagnosis》, I am very interested in your research and want to further study your work. But I have read this GitHub reposity which is the same as consistenthttps://github.com/YIKUAN8/Transformers-VQA/ , and not the specific implementation in your paper. Can you please open source code of ur job? Thanks a lot！

**Comment by masoud-monajati** [comment]
Hi There,
sorry for the delay. I'll add the code for an off-the-shell image feature extractor module shortly. given the features, you can run the script to train and evaluate.
